import type { APIRoute } from 'astro';
import { getServiceClient } from '../../../lib/supabase';

const J = { 'Content-Type': 'application/json' };
const err = (msg: string, s = 400) => new Response(JSON.stringify({ error: msg }), { status: s, headers: J });

// POST — guest taps "Show Code": creates a reveal record and returns the coupon code + confirm token
export const POST: APIRoute = async ({ request }) => {
  const { coupon_id, business_id, source } = await request.json();
  if (!coupon_id || !business_id) return err('coupon_id and business_id required');

  const service = getServiceClient();

  // Create reveal record — token is auto-generated by the DB default
  const { data: reveal, error: revealErr } = await service
    .from('partner_coupon_reveals')
    .insert({ coupon_id, business_id, source: source || null })
    .select('token')
    .single();

  if (revealErr) return err(revealErr.message, 500);

  // Increment reveal counter (non-blocking)
  service.rpc('increment_coupon_reveal', { p_coupon_id: coupon_id });

  // Fetch the coupon code to return to the guest
  const { data: coupon } = await service
    .from('partner_coupons')
    .select('code')
    .eq('id', coupon_id)
    .single();

  return new Response(JSON.stringify({
    token:       reveal.token,
    code:        coupon?.code,
    confirm_url: `/b/confirm?t=${reveal.token}`,
  }), { status: 200, headers: J });
};
